INSERT INTO CATEGORIA (NOME) VALUES ('informática');
INSERT INTO CATEGORIA (NOME) VALUES ('eletrônico');
INSERT INTO CATEGORIA (NOME) VALUES ('alimentação');
INSERT INTO CATEGORIA (NOME) VALUES ('smartphones');
